steps:
# 1. Fetch the source code
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/Manjula-86/cloudbuilddemo.git']
  

 - name: maven:3.6.0-jdk-11-slim
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']   
   
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/linen-striker-359705/docker', '--build-arg=JAR_FILE=target/build-artifact', '.']
images: ['gcr.io/linen-striker-359705/docker']
          
