steps:
# 1. Fetch the source code
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/Manjula-86/cloudbuilddemo.git']
  
- name: gcr.io/cloud-builders/mvn
   args: ['install','package', '-Dmaven.test.skip=true']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/docker', '--build-arg=JAR_FILE=target/build-artifact', '.']
images: ['gcr.io/$PROJECT_ID/docker']

          
